{% set version = "1.5.0" %}

package:
  name: pynio
  version: {{ version }}

source:
  git_url: https://github.com/NCAR/pynio.git
  git_rev: 05806a26a8676fea5832c0f270609e20df1d7276

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - gcc
    - numpy 1.7.*  # [py27]
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - libgdal 2.1.*
    - g2clib 1.6.*
    - hdfeos2
    - hdfeos5
    - jasper
    - util-linux  # [linux]
    - libuuid  # [osx]
  run:
    - python
    - numpy >=1.7  # [py27]
    - libnetcdf 4.4.*
    - hdf4
    - proj4 4.9.3
    - libgdal 2.1.*
    - g2clib 1.6.*
    - hdfeos2
    - hdfeos5
    - jasper
    - libgfortran
    - util-linux  # [linux]
    - libuuid  # [osx]

test:
  requires:
    - nose
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && nosetests  # [not win]
    - conda inspect linkages -p $PREFIX pynio  # [not win]
    - conda inspect objects -p $PREFIX pynio  # [osx]

about:
  home: http://www.pyngl.ucar.edu/Nio.shtml
  license: BSD 3-clause
  summary: 'PyNIO is a multi-format data I/O package with a NetCDF-style interface.'

extra:
  recipe-maintainers:
    - marylhaley
    - ocefpaf
    - jhamman
    - david-ian-brown
    - khallock
