{% set version = "0.9.6" %}

package:
  name: xarray
  version: {{ version }}

source:
  git_url: https://github.com/pydata/xarray.git
  git_rev: 5bd40151fd92e4342c43ba7cd6039e63e1611812

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - netcdf4
    - scipy
    - bottleneck
    - dask >=0.6
    - h5netcdf
    - cyordereddict  # [not py>=35]

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'N-D labeled arrays and datasets in Python.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
