.headers on
.mode csv
.output IRRADIANCE.csv
SELECT
	MIN(TIMESTAMP) AS TIMESTAMP,
    YEAR,
    MONTH,
    DAY,
    HOUR,
    MINUTE,
    MIN(DAYOFYEAR) AS DAYOFYEAR,
    MIN(CODE1) AS CODE1,
    MIN(CODE2) AS CODE2,
    MIN(CODE3) AS CODE3,
    AVG(UGAAPOA1IRR) AS UGAAPOA1IRR,
    AVG(UGAAPOA2IRR) AS UGAAPOA2IRR,
    AVG(UGAAPOA3IRR) AS UGAAPOA3IRR,
    AVG(UGAAPOAREFIRR) AS  UGAAPOAREFIRR ,
    AVG(UGABPOA1IRR) AS UGABPOA1IRR,
    AVG(UGABPOA2IRR) AS UGABPOA2IRR,
    AVG(UGABPOA3IRR) AS UGABPOA3IRR,
    AVG(UGABPOAREFIRR) AS UGABPOAREFIRR,
    AVG(UGADPOA1IRR) AS UGADPOA1IRR,
    AVG(UGADPOA2IRR) AS UGADPOA2IRR,
    AVG(UGADPOA3IRR) AS UGADPOA3IRR,
    AVG(UGADPOAREFIRR) AS UGADPOAREFIRR,
    AVG(UGACPOA1IRR) AS UGACPOA1IRR,
    AVG(UGACPOA2IRR) AS UGACPOA2IRR,
    AVG(UGACPOA3IRR) AS UGACPOA3IRR,
    AVG(UGACPOAREFIRR) AS UGACPOAREFIRR,
    AVG(UGAEPOA1IRR) AS UGAEPOA1IRR,
    AVG(UGAEPOA2IRR) AS UGAEPOA2IRR,
    AVG(UGAEPOA3IRR) AS UGAEPOA3IRR,
    AVG(UGAEPOAREFIRR) AS UGAEPOAREFIRR,
    AVG(UGAMET01POA1IRR) AS UGAMET01POA1IRR,
    AVG(UGAMET01POA2IRR) AS UGAMET01POA2IRR,
    AVG(UGAMET02GHIIRR) AS UGAMET02GHIIRR,
    AVG(UGAMET02DHIIRR) AS UGAMET02DHIIRR,
    AVG(UGAMET02DNIIRR) AS UGAMET02DNIIRR,
    AVG(UGAMET02FIRIRR) AS UGAMET02FIRIRR
FROM
	IRRADIANCE
GROUP BY 
	YEAR, MONTH, DAY, HOUR, MINUTE;
.output stdout