# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NaaBg8NtzUfh3LRGhc1a7EM0Tl788tJ4bnya9IbGmMY0285sLa1pbZkaAsKQsAdjt6cSbA+DmWYaTbZXmR7PrX0OrGHmhDyYCnOvkhO8jI3IKW1QNYXw6sVftux1US70Two8wH0URSZ/G2xCzynK3Mt2faA3t3Ck9i8pm44I0osxiGFjMhpNdPItOIhALxfOIVCqSSWJ4jEDNVD3XeBy3ZlzDnPzmx3A/D0Wrf71TRN7NIeoVWV0Eus8R3Ek6CbX1NSjkLhGeHVRsS5GGN0BOx6e/lK9B3cOGRo6UU1umKyD2YyIsnAsRqrFgW56vxVBO0gOBNUEOB/J6SSw20JFts4jhAJXUN2txN904vo1/tuX402HP883cyKEHixDLFqD0EDGTpUHjl9rgtv3RxpgcE4GobNMhn61nxtu3OUh9J1WnMPvBcEPwJgU77phZpf+hQdzPROTnuv500fjhh6SCnuNZjQ3EJsdNxhIApI+393tnwq/pwQtXTvgz5sQTr6tmgeQQgETcxsq7dsQFD2DkYvwqN8rMKs0MzmPASGd1xTMhcQHAfMgya5Wu1c3R3zGxDZRc+Aa3xPuYFuVjfrqgknY5/Ahrh9hh3ZYPOH76Kid0gWLJMXCe8MvdiScSI9ers79CuFI881UsbjyL+svdBipG+dQx4BT3QL68JnfGfI="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
