travis:
  secure:
    BINSTAR_TOKEN: NaaBg8NtzUfh3LRGhc1a7EM0Tl788tJ4bnya9IbGmMY0285sLa1pbZkaAsKQsAdjt6cSbA+DmWYaTbZXmR7PrX0OrGHmhDyYCnOvkhO8jI3IKW1QNYXw6sVftux1US70Two8wH0URSZ/G2xCzynK3Mt2faA3t3Ck9i8pm44I0osxiGFjMhpNdPItOIhALxfOIVCqSSWJ4jEDNVD3XeBy3ZlzDnPzmx3A/D0Wrf71TRN7NIeoVWV0Eus8R3Ek6CbX1NSjkLhGeHVRsS5GGN0BOx6e/lK9B3cOGRo6UU1umKyD2YyIsnAsRqrFgW56vxVBO0gOBNUEOB/J6SSw20JFts4jhAJXUN2txN904vo1/tuX402HP883cyKEHixDLFqD0EDGTpUHjl9rgtv3RxpgcE4GobNMhn61nxtu3OUh9J1WnMPvBcEPwJgU77phZpf+hQdzPROTnuv500fjhh6SCnuNZjQ3EJsdNxhIApI+393tnwq/pwQtXTvgz5sQTr6tmgeQQgETcxsq7dsQFD2DkYvwqN8rMKs0MzmPASGd1xTMhcQHAfMgya5Wu1c3R3zGxDZRc+Aa3xPuYFuVjfrqgknY5/Ahrh9hh3ZYPOH76Kid0gWLJMXCe8MvdiScSI9ers79CuFI881UsbjyL+svdBipG+dQx4BT3QL68JnfGfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
