travis:
  secure:
    BINSTAR_TOKEN: gq6XJoQh6rCGk3o61RuHtJp+rUaRC3lxem+76/1tGrJPMkRZc2trxQFl0eEzKDxudRUnpLFrQaYRi2Looy7hjpzsqPKkOPdpVjg76UfkGbBe3xgO+ZuPO6EN89FEPS9EDmd9uAeAuqkM4E53P+6/rxFVtJh4hQjlJGr0syTBlK9hofYvx7nEMudQWAFvm6uxEJVBp7itQzrKngnDa8ZhhhxHxJKEIvh0BP1X1YsgrJrCmAy0+Ifh/I8wBYJYLqO7v/9WHWm9FO/ffIzNFIlGFwjZf5uNmYNSRQi/hi4NEMOAWes02rpmDvioJeXIb1YYlfa13wFMjVxCNrXd9Sd6fxGiLRBduDx4Bpp2a1SqwPu6Y3GVKc1BmnAhQzRjkg3m81K4rihaBZQ9l3ZmoatIRm3tsjM1YSEhJqGmGBgE6xv1rIJmlJduAyLoBwY0MELZfHxn6gaJEbQvP2yFFScLQsZ2Pn/v5Cy+m2Ov3soPCCS3tZF+v3Qa6qGw8gUZ2pgGnBe2sgqkk7khm8+Oq4v9NH+ibydwoT6gUrNh+XOXAu2Bo6YtIIA8TgHWYCglILh9xg4T1c360wm47xCgHqbWZO8JNO3/1HLjaTn5JVgFx3IpKJNKi3KzUUcv7SSF6cWFrj5fuEebnGJUcQRQBffFzucC86ff12aBwmoUrRjn+5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
